.TH DEX 1 dex\-VERSION
.SH NAME
dex \- DesktopEntry Execution
.SH SYNOPSIS
.B dex
.RB [options]\ [DesktopEntryFile\ [DesktopEntryFile ...]]
.SH DESCRIPTION
dex, DesktopEntry Execution, is a program to generate and execute
DesktopEntry files of the type Application.
.SH OPTIONS
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-a, \-\-autostart
autostart programs
.TP
.B \-c CREATE [CREATE ...], \-\-create CREATE [CREATE ...]
create a DesktopEntry file for the given program. If a second argument
is provided it's taken as output filename or written to stdout (filname:
\-). By default a new file with the postfix .desktop is created
.TP
.B \-d, \-\-dry\-run
dry run, don't execute any command
.TP
.B \-e ENVIRONMENT, \-\-environment ENVIRONMENT
specify the Desktop Environment an autostart should be performed for;
works only in combination with \-\-autostart
.TP
.B \-t, \-\-target-directroy DIRECTORY
create files in target directory
.TP
.B \-\-test
perform a self\-test
.TP
.B \-v, \-\-verbose
verbose output
.TP
.B \-V, \-\-version
display version information
.SH EXAMPLES
.TP
Perform an autostart/execute all programs in the autostart folders.
.B dex -a
.TP
Preview the programs would be executed in a regular autostart.
.B dex -ad
.TP
Preview the programs would be executed in a GNOME specific autostart.
.B dex -ad -e GNOME
.TP
Create a DesktopEntry for a program in the current directory.
.B dex -c /usr/bin/skype
.TP
Create a DesktopEntry for a programs in autostart directroy.
.B dex -t ~/.config/autostart -c /usr/bin/skype /usr/bin/nm-applet
.TP
Execute a single program from command line and enable verbose output.
.B dex -v skype.desktop
